server:
  port: 8080
  shutdown: graceful

  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true


spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  jpa:
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 10